### PR TITLE
fuzzers: 074: fix path to generate_after_dump

### LINKED ISSUE #515: fuzzer 074 fails on generate_after_dump
```
+ cd ..
+ ./generate_after_dump.sh
generate.sh: line 7: ./generate_after_dump.sh: No such file or directory 
```
it seems commit 19a93121a6b45a3236eeb2d0445b8b86b771fc85 introduced this bug
I've tested this with zynq7 settings

### PR DESCRIPTION
**Pull request by kgugala**
fixes #515

### CODE REVIEW

File: fuzzers/074-dump_all/generate.sh [hunk 1]
```diff
@@ -4,4 +4,4 @@ source ${XRAY_GENHEADER}
 
 ${XRAY_VIVADO} -mode batch -source $FUZDIR/generate.tcl
 
-cd .. && ./generate_after_dump.sh
+cd ../.. && ./generate_after_dump.sh
```
Comment (litghost) [inline fuzzers/074-dump_all/generate.sh]: $FUZDIR?

Comment (kgugala) [reply fuzzers/074-dump_all/generate.sh]: makes sense
