### PR TITLE
zybo: Fix Zybq Zynq-7 roi_harness

### LINKED ISSUE #703: Building roi_harness for zybo fails
```
WARNING: [Vivado 12-3286] Net, clk, could not be marked fixed.  The net is either fully contained within a site or is unrouted.
WARNING: [Vivado 12-3286] Net, din[0], could not be marked fixed.  The net is either fully contained within a site or is unrouted.
WARNING: [Vivado 12-3286] Net, din[1], could not be marked fixed.  The net is either fully contained within a site or is unrouted.
WARNING: [Vivado 12-3286] Net, din[2], could not be marked fixed.  The net is either fully contained within a site or is unrouted.
WARNING: [Vivado 12-3286] Net, din[3], could not be marked fixed.  The net is either fully contained within a site or is unrouted.
WARNING: [Vivado 12-3286] Net, dout[0], could not be marked fixed.  The net is either fully contained within a site or is unrouted.
WARNING: [Vivado 12-3286] Net, dout[1], could not be marked fixed.  The net is either fully contained within a site or is unrouted.
WARNING: [Vivado 12-3286] Net, dout[2], could not be marked fixed.  The net is either fully contained within a site or is unrouted.
WARNING: [Vivado 12-3286] Net, dout[3], could not be marked fixed.  The net is either fully contained within a site or is unrouted.
WARNING: [Vivado 12-3286] Net, <const1>, could not be marked fixed.  The net is either fully contained within a site or is unrouted.
# write_checkpoint -force design.dcp
Writing placer database...
Writing XDEF routing.
Writing XDEF routing logical nets.
Writing XDEF routing special nets.
Write XDEF Complete: Time (s): cpu = 00:00:00.02 ; elapsed = 00:00:00.01 . Memory (MB): peak = 2017.582 ; gain = 0.000 ; free physical = 124649 ; free virtual = 342994
INFO: [Common 17-1381] The checkpoint '/big/github/SymbiFlow/prjxray-zynq/minitests/roi_harness/build/design.dcp' has been generated.
# write_bitstream -force design.bit
Command: write_bitstream -force design.bit
Attempting to get a license for feature 'Implementation' and/or device 'xc7z010-clg400'
INFO: [Common 17-349] Got license for feature 'Implementation' and/or device 'xc7z010-clg400'
Running DRC as a precondition to command write_bitstream
Command: report_drc (run_mandatory_drcs) for: bitstream_checks
INFO: [DRC 23-27] Running DRC with 8 threads
WARNING: [DRC RPBF-3] IO port buffering is incomplete: Device port din[0] expects both input and output buffering but the buffers are incomplete.
WARNING: [DRC RPBF-3] IO port buffering is incomplete: Device port din[1] expects both input and output buffering but the buffers are incomplete.
WARNING: [DRC RPBF-3] IO port buffering is incomplete: Device port din[2] expects both input and output buffering but the buffers are incomplete.
WARNING: [DRC RPBF-3] IO port buffering is incomplete: Device port din[3] expects both input and output buffering but the buffers are incomplete.
WARNING: [DRC ZPS7-1] PS7 block required: The PS7 cell must be used in this Zynq design in order to enable correct default configuration.
report_drc (run_mandatory_drcs) completed successfully
INFO: [Vivado 12-3199] DRC finished with 0 Errors, 5 Warnings
INFO: [Vivado 12-3200] Please refer to the DRC report (report_drc) for more information.
INFO: [Project 1-821] Please set project.enableDesignId to be 'true'.
INFO: [Designutils 20-2272] Running write_bitstream with 8 threads.
Loading data files...
Loading site data...
Loading route data...
Processing options...
Creating bitmap...
Creating bitstream...
Writing bitstream ./design.bit...
INFO: [Vivado 12-1842] Bitgen Completed Successfully.
INFO: [Project 1-120] WebTalk data collection is mandatory when using a WebPACK part without a full Vivado license. To see the specific WebTalk data collected for your design, open the usage_statistics_webtalk.html or usage_statistics_webtalk.xml file in the implementation directory.
INFO: [Common 17-186] '/big/github/SymbiFlow/prjxray-zynq/minitests/roi_harness/build/design/usage_statistics_webtalk.xml' has been successfully sent to Xilinx on Fri Mar  8 00:34:01 2019. For additional details about this file, please refer to the WebTalk help file at /opt/Xilinx/Vivado/2017.2/doc/webtalk_introduction.html.
9 Infos, 5 Warnings, 0 Critical Warnings and 0 Errors encountered.
write_bitstream completed successfully
write_bitstream: Time (s): cpu = 00:00:09 ; elapsed = 00:00:09 . Memory (MB): peak = 2351.000 ; gain = 333.418 ; free physical = 124630 ; free virtual = 342974
INFO: [Common 17-206] Exiting Vivado at Fri Mar  8 00:34:01 2019...
++ fgrep CRITICAL vivado.log
+ test -z ''
+ /big/github/SymbiFlow/prjxray-zynq/build/tools/bitread --part_file /big/github/SymbiFlow/prjxray-zynq/database/zynq7/xc7z010clg400-1.yaml -F 0x00000000:0xffffffff -o design.bits -z -y design.bit
Bitstream size: 2083839 bytes
Config size: 520922 words
Number of configuration frames: 5144
DONE
+ python3 /big/github/SymbiFlow/prjxray-zynq/utils/bit2fasm.py --verbose design.bit
+ python3 /big/github/SymbiFlow/prjxray-zynq/utils/fasm2frames.py design.fasm design.frm
+ PYTHONPATH=/big/github/SymbiFlow/prjxray-zynq:/big/github/SymbiFlow/prjxray-zynq/third_party/fasm:/big/github/SymbiFlow/prjxray-zynq:/big/github/SymbiFlow/prjxray-zynq/third_party/fasm:/big/github/SymbiFlow/prjxray-zynq:/big/github/SymbiFlow/prjxray-zynq/third_party/fasm::/big/github/SymbiFlow/prjxray-zynq/utils
+ python3 ../create_design_json.py --design_info_txt design_info.txt --design_txt design.txt --pad_wires design_pad_wires.txt --design_fasm design.fasm
Traceback (most recent call last):
  File "../create_design_json.py", line 119, in <module>
    main()
  File "../create_design_json.py", line 92, in main
    unknown_base_address)
AssertionError: Found unknown bit in base address 0x00001380
Makefile:14: recipe for target 'build/design.json' failed
make: *** [build/design.json] Error 1
```

### PR DESCRIPTION
**Pull request by kgugala**
fixes #703

### CODE REVIEW

File: settings/zynq7.sh [hunk 1]
```diff
@@ -9,7 +9,7 @@ export XRAY_ROI_TILEGRID="SLICE_X0Y0:SLICE_X43Y99 RAMB18_X0Y0:RAMB18_X2Y39 RAMB3
 export XRAY_ROI="SLICE_X00Y50:SLICE_X43Y99 RAMB18_X0Y20:RAMB18_X2Y39 RAMB36_X0Y10:RAMB36_X2Y19 IOB_X0Y50:IOB_X0Y99"
 
 # Most of CMT X0Y2.
-export XRAY_ROI_GRID_X1="0"
+export XRAY_ROI_GRID_X1="83"
```
Comment (litghost) [inline settings/zynq7.sh]: That seems like a preset small ROI?  How many CLB's are in this ROI?
