### PR TITLE
fuzzers: int_loop: exit on empty todo

### LINKED ISSUE #692: Fuzzers fail on generating DB when empty todo.txt was generated
When all the INTs were already solved the generated todo.txt is empty. Fuzzers still attempt to push the db ending in mergedb error.

### PR DESCRIPTION
**Pull request by kgugala**
fixes #692

### CODE REVIEW

File: fuzzers/int_loop.sh [hunk 1]
```diff
@@ -43,6 +43,10 @@ i=1
 while true; do
     ${MAKE} ITER=$i cleaniter
     ${MAKE} ITER=$i build/todo.txt
+    if [ ! -s build/todo.txt ]; then
```
Comment (litghost) [inline fuzzers/int_loop.sh]: I don't think this helps, because the problem is that pushdb fails because there is nothing to push.

Comment (kgugala) [reply fuzzers/int_loop.sh]: Actually it helps in a case where empty todo was generated in the first iteration. Currently if such a situation happens the code breaks the loop and goes directly to pushdb and fails on empty segbits.

I'll extend the if empty todo with first iteration check.

Comment (kgugala) [reply fuzzers/int_loop.sh]: done, now the check is performed only for the first loop iteration
